### ISSUE TITLE
Suricata 7.0.2 - crash with interfaces containing dots (bond1.30)

### ISSUE THREAD

**Issue by vpiserchia** [corelight/suricata_exporter#12]
Testing v0.2.1 of suricata_exporter against Suricata 7.0.2 produces this error:

```
panic: interface conversion: interface {} is nil, not map[string]interface {}
[](url)
goroutine 21 [running]:
main.handleWorkerThread(0x7f1620?, {0xc000147dc0, 0xa}, 0x7?)
	/home/runner/work/suricata_exporter/suricata_exporter/main.go:554 +0x10c5
main.produceMetrics(0xc00011e0c0?, 0xc0001322a0?)
	/home/runner/work/suricata_exporter/suricata_exporter/main.go:744 +0x278
main.(*suricataCollector).Collect(0xc00011d900, 0xc000094760?)
	/home/runner/work/suricata_exporter/suricata_exporter/main.go:791 +0x14f
github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func1()
	/home/runner/go/pkg/mod/github.com/prometheus/client_golang@v1.11.0/prometheus/registry.go:448 +0x11a
created by github.com/prometheus/client_golang/prometheus.(*Registry).Gather
	/home/runner/go/pkg/mod/github.com/prometheus/client_golang@v1.11.0/prometheus/registry.go:457 +0x4c5
```

Attached the [dump-counters.json](https://github.com/corelight/suricata_exporter/files/14143585/dump-counters.json)

**Comment by awelzel** [comment]
Hello @vpiserchia - Does this happen for you also with non-bond interfaces, too?

I'm looking at `dump-counters.json` output you provided (thanks!) and it looks like the `threads["W#01-bond"]` has a single "30" key that then nests the actual thread data:
```
{
  "W#01-bond1": {
    "30": {
      "capture": {
        "kernel_packets": 247478455,
        "kernel_drops": 186199,
       ...
      },
      "tcp": {
        "syn": 916622,
        "synack": 803543,
```

Honestly, to me this looks like a bug with the Suricata stats. It's not even clear what the meaning of the "30" is and they shouldn't be changing their stats format in a patch release anyhow.

@jlucovsky @victorjulien could you take a peek what happened in 7.0.3 with the stats code that such a format is produced?

**Comment by vpiserchia** [comment]
@awelzel thanks for you quick response.

Indeed this is linked to the use of bond interfaces. Without bond the Json structure changes completely to this one:
```
    "threads": {
      "W#01-bond1": {
        "capture": {
          "kernel_packets": 27888,
          "kernel_drops": 0,
          "errors": 0,
          "afpacket": {
            "busy_loop_avg": 0,
            "polls": 2554,
            "poll_signal": 0,
            "poll_timeout": 203,
            "poll_data": 2351,
            "poll_errors": 0,
            "send_errors": 0
          }
        },
```

and the ```suricata_exporter``` works correctly:
```
suricata_app_layer_flows_total{app="bittorrent-dht",thread="W#01-bond1"} 0
suricata_app_layer_flows_total{app="dcerpc_tcp",thread="W#01-bond1"} 0
suricata_app_layer_flows_total{app="dcerpc_udp",thread="W#01-bond1"} 0
suricata_app_layer_flows_total{app="dhcp",thread="W#01-bond1"} 0
suricata_app_layer_flows_total{app="dns_tcp",thread="W#01-bond1"} 2
suricata_app_layer_flows_total{app="dns_udp",thread="W#01-bond1"} 347
suricata_app_layer_flows_total{app="enip_tcp",thread="W#01-bond1"} 0
suricata_app_layer_flows_total{app="enip_udp",thread="W#01-bond1"} 0
suricata_app_layer_flows_total{app="failed_tcp",thread="W#01-bond1"} 20
suricata_app_layer_flows_total{app="failed_udp",thread="W#01-bond1"} 15
suricata_app_layer_flows_total{app="ftp",thread="W#01-bond1"} 0
```

**Comment by awelzel** [comment]
> It is the bond interface name:

Ah. Thanks for checking. Suspect this is also an issue with prior Suricata versions? Or has that only started with 7.0.3? Do you know?

Anyhow, please report this to the Suricata team. suricata_exporter crashing is unfortunate, but it's just a signal that the stats produced by Suricata are a bit broken.

**Comment by vpiserchia** [comment]
https://redmine.openinfosecfoundation.org/issues/6732

**Comment by victorjulien** [comment]
FYI there is no 7.0.3 yet.

**Comment by vpiserchia** [comment]
@victorjulien of course you're totally right. I messed up here. it is the 7.0.2. Going to edit both the issues.

**Comment by awelzel** [comment]
@vpiserchia - I'm closing this. Upcoming Suricata 7.0.4 should have this fixed. Thanks for the report.
