### ISSUE TITLE
Warn Suricata 7.0.3

### ISSUE THREAD

**Issue by spinenkoia** [corelight/suricata_exporter#15]
Errors when collecting metrics with Suricata 7.0.3

```
WARN: Threads entry memcap_pressure not a map[string]
Threads entry memcap_pressure_max not a map[string]
```
suricata version - 7.0.3
suricata_exporter version - 0.3.0

**Comment by awelzel** [comment]
Yeah, IMO that's a bug on the Suricata side: https://redmine.openinfosecfoundation.org/issues/6398

**Comment by spinenkoia** [comment]
Understood, thanks

**Comment by Icosa-Consulting** [comment]
Is there a way to squelch this particular message?, it's filling up my journal logs.

**Comment by awelzel** [comment]
> Is there a way to squelch this particular message?, it's filling up my journal logs.

Should be gone with 0.4.1.
