### ISSUE TITLE
Thread metrics not collected in NFQueue runmode

### ISSUE THREAD

**Issue by rowecharles** [corelight/suricata_exporter#17]
- Suricata version: `v7.0.1`
- Suricata runmode: nfqueue
- Suricata Exporter version: `v0.3.0`

After switching Suricata to NFQueue runmode the thread metrics are no longer collected.  There are warnings in the logs such as:

```
2024/05/28 22:52:19 WARN: Unhandled thread: W-NFQ#0
2024/05/28 22:52:19 WARN: Unhandled thread: W-NFQ#1
2024/05/28 22:52:19 WARN: Unhandled thread: W-NFQ#2
2024/05/28 22:52:19 WARN: Unhandled thread: W-NFQ#3
```

The thread metrics are available from Suricata however the thread names have prefix `W-NFQ#`:

```
$ suricatasc -c dump-counters | jq
...
    "threads": {
      "W-NFQ#0": {
        "ips": {
          "accepted": 25624776,
          "blocked": 1457,
...
```

The exporter expects worker threads to have a prefix `W#` which is not the case when in nfqueue runmode:

https://github.com/corelight/suricata_exporter/blob/998e7d9ed8e8d37ad91f7fd7e563d37a6015b8a4/main.go#L756

**Comment by awelzel** [comment]
@rowecharles / @Neurozone - could you check if v0.4.0-rc1 works for you? I've also added the `ips` section as individual packet counter metrics. Would be good to get some feedback if this works for you now (possibly attaching a dump-counters.json output with your expectations. Thanks!

**Comment by Neurozone** [comment]
Will check tomorrow :)

**Comment by rowecharles** [comment]
@awelzel , I've validated on our setup and confirmed that all the thread metrics are now getting collected including the new IP packet counter metrics.

Thanks a lot for the fix and all the work on the project!

**Comment by awelzel** [comment]
Thanks, I've pushed 0.4.0 now.

**Comment by Neurozone** [comment]
I also confirm that I don't have theses warnings anymore with version 0.4.
But I have other warnings. I will open another issue for that
