### ISSUE TITLE
Suricata and prometheus

### ISSUE THREAD

**Issue by AsakaLan** [corelight/suricata_exporter#6]
Hello, is it still possible to adapt this to the latest version of Suricata and export it to prometheus?

**Comment by AsakaLan** [comment]
@awelzel Thank you very much for getting back to me, my problem is that I turned on. /suricata_exporter and then use curl -s localhost:9917/metrics | grep kernel_packets_total without output.So I'm wondering if I haven't configured it properly myself or if it's a problem with the plugin itself. Thank you very much

**Comment by AsakaLan** [comment]
![image](https://user-images.githubusercontent.com/103125315/218632307-e3e115b2-d2b2-4823-8d25-ae8579052925.png)

**Comment by AsakaLan** [comment]
@awelzel when i use ./suricata_exporter -web.listen-address “localhost:9917” and use curl -s localhost:9917/metrics | grep kernel_packets_total the terminal show this 
![image](https://user-images.githubusercontent.com/103125315/218632527-14eb4823-8715-4f9f-8573-a0df30ddd180.png)

**Comment by awelzel** [comment]
@AsakaLan - this indicates that suricata_exporter is unable to find Suricata's commands socket. Could you verify that  `/var/run/suricata.socket` exists? If it's located at a different path, use `-suricata.socket-path /path/to/socket`. If it's not enabled in your Suricata config, enable it.

In suricata.yaml:
```
unix-command:
  enabled: yes
  #filename: custom.socket # use this to specify an alternate file
```

See also: https://suricata.readthedocs.io/en/suricata-6.0.0/unix-socket.html#introduction

**Comment by AsakaLan** [comment]
I have configured this even I have made more changes but still have problems 
![image](https://user-images.githubusercontent.com/103125315/218700203-4cf9acb1-5ded-48b3-a330-88613ef84201.png)
![image](https://user-images.githubusercontent.com/103125315/218700279-dbc1b1e9-3036-4349-aa8e-425170b919ad.png)

**Comment by AsakaLan** [comment]
@awelzel  have configured this even I have made more changes but still have problems.
![image](https://user-images.githubusercontent.com/103125315/218700918-caeb6155-e026-4e9f-b24b-1b6026aef0b0.png)
![image](https://user-images.githubusercontent.com/103125315/218700966-1e826aec-9135-4f18-8e54-6783cafb86dd.png)

**Comment by awelzel** [comment]
If you configured the name in Suricata to be `custom.socket`, you'll need to start `suricata_exporter -suricata.socket-path /var/run/custom.socket`.

**Comment by AsakaLan** [comment]
![image](https://user-images.githubusercontent.com/103125315/218701920-20965f31-6354-44ca-a9e3-5492d4f7fd38.png)
I've changed the configuration and still get this error when I start this way, it's annoying。
![image](https://user-images.githubusercontent.com/103125315/218702294-38258070-51d9-4f38-ba6b-936f4442b0f5.png)

**Comment by awelzel** [comment]
Hmm, could you run `ls -lha /var/run` and see if the socket exists and check its permissions. Then also, see if there are any helpful messages in the Suricata stderr output or log when you restart, or when you run the `curl` command to the exporter.

Which version of Suricata are you using?

**Comment by AsakaLan** [comment]
my Suricata version is  Suricata 6.0.10
ls -lha /var/run is 
![image](https://user-images.githubusercontent.com/103125315/218704231-6ca7b5af-ddf2-4b21-9798-a9b746429bc7.png)

**Comment by AsakaLan** [comment]
The problem has not been solved yet but thank you very much, you are a wonderful person and I will try again to see if there is another way！

**Comment by AsakaLan** [comment]
I'm a beginner to this so I'm probably not familiar with many things, but thank you for helping me, haha!

**Comment by awelzel** [comment]
Okay. No worries.

Maybe first try to get `suricatasc` to work with Suricata as described here: https://suricata.readthedocs.io/en/suricata-6.0.0/unix-socket.html#introduction

Once you're able to gather statistics with the `suricatasc` command `dump-counters` and have familiarized yourself with Suricata a bit, try the `suricata_exporter` again. Have fun!

**Comment by AsakaLan** [comment]
Haha I solved the problem, I hadn't found the default socket path for my suricata until I found it in /var/run/suricata/suricata-command.socket, so this result means it worked!
![image](https://user-images.githubusercontent.com/103125315/218907905-295e79ae-31e2-4122-a9ab-8492c6591148.png)

**Comment by AsakaLan** [comment]
Thank you very much, this tool will help me to integrate it into Prometheus later!

**Comment by AsakaLan** [comment]
Hello brother, if I now simulate a suricata message and it generates the corresponding json information, how can I export this information using this tool
![image](https://user-images.githubusercontent.com/103125315/219257155-31c88214-7fad-4e9d-9e54-d61b2d7fb39f.png)

**Comment by awelzel** [comment]
Great - happy to hear you're making progress.

> Hello brother, if I now simulate a suricata message and it generates the corresponding json information, how can I export this information using this tool

This tool is not made for that - it's purpose is to expose Suricata metrics/stats to Prometheus. For eve.json query/parsing, you may want to look into storing the eve.json content in Elasticsearch, Loki, Splunk, etc.
